import type { MonitoredApi } from "@/types/api"

export const initialApis: MonitoredApi[] = [
  {
    id: 1,
    name: "Production API",
    url: "https://api.example.com/health",
    method: "GET",
    status: "UP",
    responseTime: 124,
    uptime: "99.99",
    lastChecked: "2 minutes ago",
    lastCheckedAt: "2026-10-06T02:07:28.000000Z",
    timeout: 10,
    interval: 5,
  },
  {
    id: 2,
    name: "User API",
    url: "https://api.example.com/users",
    method: "GET",
    status: "UP",
    responseTime: 87,
    uptime: "99.95",
    lastChecked: "5 minutes ago",
    lastCheckedAt: "2026-10-06T02:04:28.000000Z",
    timeout: 10,
    interval: 5,
  },
  {
    id: 3,
    name: "Payment API",
    url: "https://api.example.com/payment",
    method: "GET",
    status: "DOWN",
    responseTime: null,
    uptime: "98.12",
    lastChecked: "12 minutes ago",
    lastCheckedAt: "2026-10-06T01:57:28.000000Z",
    timeout: 10,
    interval: 5,
  },
  {
    id: 4,
    name: "Analytics API",
    url: "https://api.example.com/analytics",
    method: "GET",
    status: "DEGRADED",
    responseTime: 843,
    uptime: "99.41",
    lastChecked: "8 minutes ago",
    lastCheckedAt: "2026-10-06T02:01:28.000000Z",
    timeout: 10,
    interval: 5,
  },
]